#! /bin/sh

# Author: Li Zheng <flyskywhy@gmail.com>
# Automatically clone repositorys that current project needed.

GIT_SERVER='git@192.0.4.104:/pub/gittrees/'

proj_clone ()
{
    mkdir -p $3
    git clone $GIT_SERVER/$1.git -b $2 $3/$4
}

if [ $# = 0 ] ; then
    echo "help"
elif [ $1 = clone ] ; then
    echo "proj clone"
    proj_clone android-apps-host adb-gb apps adb
elif [ $1 = pull ] ; then
    echo "proj pull"
fi
