#! /bin/sh

# Author: Li Zheng <flyskywhy@gmail.com>
# Automatically clone repositorys that current project needed.

GIT_SERVER='git://github.com/flyskywhy'

# Under Linux, if USE_MINGW is set here manually, or
# under Windows, it will build Windows application.
#
# On all modern variants of Windows (including Cygwin and Wine)
# the OS environment variable is defined to 'Windows_NT'
if [ 777${OS} = 777"Windows_NT" ]; then
export USE_MINGW=1
else
export USE_MINGW=
fi

proj_help ()
{
    echo "proj clone       - clone repositorys that current project needed"
    echo "proj pull        - fetch remote and automatically merge"
    echo "proj fetch       - just fetch remote, no merge"
    echo "proj help        - show this help message"
}

proj_clone ()
{
    mkdir -p $3
    git clone $GIT_SERVER/$1.git -b $2 $3/$4
    echo
}

proj_pull ()
{
    echo "$1/$2"
    cd  $1/$2
    git pull origin
    cd -
    echo
}

proj_fetch ()
{
    echo "$1/$2"
    cd  $1/$2
    git remote update
    cd -
    echo
}

if [ $# = 0 ] ; then
    proj_help
elif [ $1 = clone ] ; then
#   proj_clone romete_repository branch folder local_repository
    proj_clone android-apps-host adb-gb apps adb
    proj_clone android-ndk-r7b master tools android-ndk-r7b
if [ -n "$USE_MINGW" ]; then
    proj_clone android-sdk windows tools android-sdk
    proj_clone eclipse win32 tools eclipse
else
    proj_clone android-sdk linux tools android-sdk
    proj_clone eclipse linux32 tools eclipse
fi
elif [ $1 = pull ] ; then
    proj_pull apps adb
    proj_pull tools android-ndk-r7b
    proj_pull tools android-sdk
    proj_pull tools eclipse
elif [ $1 = fetch ] ; then
    proj_fetch apps adb
    proj_fetch tools android-ndk-r7b
    proj_fetch tools android-sdk
    proj_fetch tools eclipse
else
    proj_help
fi
