#! /bin/sh

# Author: Li Zheng <flyskywhy@gmail.com>
# Automatically clone repositorys that current project needed.

GIT_SERVER='git://github.com/flyskywhy'

# Under Linux, if USE_MINGW is set here manually, or
# under Windows, it will build Windows application.
#
# On all modern variants of Windows (including Cygwin and Wine)
# the OS environment variable is defined to 'Windows_NT'
if [ 777${OS} = 777"Windows_NT" ]; then
export USE_MINGW=1
else
export USE_MINGW=
fi

proj_help ()
{
    echo "proj clone       - clone repositorys that current project needed"
    echo "proj pull        - fetch remote and automatically merge"
    echo "proj fetch       - just fetch remote, no merge"
    echo "proj help        - show this help message"
}

proj_clone ()
{
    mkdir -p $3
    if [ -z $5 ]; then
        git clone $GIT_SERVER/$1.git -b $2 $3/$4
    else
        git clone $5/$1.git -b $2 $3/$4
    fi
    echo
}

proj_pull ()
{
    echo "$1/$2"
    cd  $1/$2
    git pull origin
    cd -
    echo
}

proj_fetch ()
{
    echo "$1/$2"
    cd  $1/$2
    git remote update
    cd -
    echo
}

if [ $# = 0 ] ; then
    proj_help
elif [ $1 = clone ] ; then
#   proj_clone remote_repository branch folder local_repository another_GIT_SERVER_if_needed
    proj_clone ecos microblaze . ecos
    proj_clone flyskywhys-mbref master . mbref 'git://gitorious.org/~flyskywhy/mbref'
    proj_clone ecos_app_base master apps ecos_app_base
    proj_clone yaffs-ecoscentric-gpl master . yaffs-ecoscentric-gpl
    proj_clone ecos-htdocs master . htdocs
    proj_clone wxWidgets WX_2_8_8 tools wxWidgets
    proj_clone makefile master tools makefile
if [ -n "$USE_MINGW" ]; then
    proj_clone ecos-tools windows tools ecos-tools
    proj_clone eclipse win32 tools eclipse
    proj_clone mipsisa32-elf windows tools mipsisa32-elf
    proj_clone microblazeel-unknown-linux-gnu windows tools microblazeel-unknown-linux-gnu
    proj_clone i386-elf windows tools i386-elf
    proj_clone arm-eabi windows tools arm-eabi
else
    proj_clone ecos-tools linux tools ecos-tools
    proj_clone eclipse linux32 tools eclipse
    proj_clone mipsisa32-elf linux tools mipsisa32-elf
    proj_clone microblazeel-unknown-linux-gnu linux tools microblazeel-unknown-linux-gnu
    proj_clone i386-elf linux tools i386-elf
    proj_clone arm-eabi linux tools arm-eabi
fi
elif [ $1 = pull ] ; then
    proj_pull . ecos
    proj_pull . mbref
    proj_pull apps ecos_app_base
    proj_pull . yaffs-ecoscentric-gpl
    proj_pull . htdocs
    proj_pull tools wxWidgets
    proj_pull tools makefile
    proj_pull tools ecos-tools
    proj_pull tools eclipse
    proj_pull tools mipsisa32-elf
    proj_pull tools microblazeel-unknown-linux-gnu
    proj_pull tools i386-elf
    proj_pull tools arm-eabi
elif [ $1 = fetch ] ; then
    proj_fetch . ecos
    proj_fetch . mbref
    proj_fetch apps ecos_app_base
    proj_fetch . yaffs-ecoscentric-gpl
    proj_fetch . htdocs
    proj_fetch tools wxWidgets
    proj_fetch tools makefile
    proj_fetch tools ecos-tools
    proj_fetch tools eclipse
    proj_fetch tools mipsisa32-elf
    proj_fetch tools microblazeel-unknown-linux-gnu
    proj_fetch tools i386-elf
    proj_fetch tools arm-eabi
else
    proj_help
fi
